# Generated by Django 5.1.2 on 2024-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("numeroDocumento", models.IntegerField()),
                ("tipoDocumento", models.TextField()),
                ("nombreUsuario", models.CharField(max_length=100)),
                ("empresaAsociada", models.CharField(max_length=100)),
                ("correo", models.CharField(max_length=100)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
                ("planEmpresarial", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="IncidenteCorreo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("revisado", models.BooleanField(default=False)),
                ("correoUsuario", models.CharField(max_length=20)),
                ("fechaCreacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
